# Generated by Django 5.2.4 on 2025-08-10 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='نام کاربر')),
                ('FamilyName', models.CharField(max_length=100, verbose_name='نام خانوادگی کاربر')),
                ('Gender_status', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True, verbose_name='جنسیت کاربر')),
                ('ProfileImage', models.ImageField(upload_to='ProfileImage/', verbose_name='پروفایل')),
                ('Credit', models.IntegerField(default=0, verbose_name='اعتبار کاربر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربری')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربر',
            },
        ),
    ]
