# Generated by Django 5.2.4 on 2025-08-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='concertmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('SingerName', models.CharField(max_length=100)),
                ('Lenght', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='locationmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('Capacity', models.IntegerField()),
            ],
        ),
    ]
