# Generated by Django 5.2.4 on 2025-08-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0002_locationmodel_phone_timemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertmodel',
            name='test',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
