# Generated by Django 5.2.4 on 2025-08-06 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0003_concertmodel_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('FamilyName', models.CharField(max_length=100)),
                ('Gender_status', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('ProfileImage', models.ImageField(upload_to='ProfileImage/')),
            ],
        ),
        migrations.AddField(
            model_name='concertmodel',
            name='Poster',
            field=models.ImageField(null=True, upload_to='PosterImage/'),
        ),
        migrations.AddField(
            model_name='timemodel',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Start'), (2, 'End'), (3, 'Cancel'), (4, 'Sale')], null=True),
        ),
        migrations.CreateModel(
            name='Ticketmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('TicketImage', models.ImageField(upload_to='TicketImage/')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.profilemodel')),
                ('Time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.timemodel')),
            ],
        ),
    ]
