# Generated by Django 5.2.4 on 2025-08-07 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0004_profilemodel_concertmodel_poster_timemodel_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertmodel',
            options={'verbose_name': 'کنسرت', 'verbose_name_plural': 'کنسرت'},
        ),
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'verbose_name': 'مکان برگزای کنسرت', 'verbose_name_plural': 'مکان برگزای کنسرت'},
        ),
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل کاربر'},
        ),
        migrations.AlterModelOptions(
            name='ticketmodel',
            options={'verbose_name': 'بلیط کنسرت', 'verbose_name_plural': 'بلیط کنسرت'},
        ),
        migrations.AlterModelOptions(
            name='timemodel',
            options={'verbose_name': 'زمان فروش بلیت کنسرت', 'verbose_name_plural': 'زمان فروش بلیت کنسرت'},
        ),
        migrations.RemoveField(
            model_name='concertmodel',
            name='test',
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Lenght',
            field=models.IntegerField(verbose_name='طول زمان برگزاری کنسرت'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نام کنسرت'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Poster',
            field=models.ImageField(null=True, upload_to='PosterImage/', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='SingerName',
            field=models.CharField(max_length=100, verbose_name='نام خواننده'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Address',
            field=models.CharField(max_length=200, verbose_name='آدرس محل برگزاری کنسرت'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Capacity',
            field=models.IntegerField(verbose_name='ظرفیت سالن'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نام محل برگزاری کنسرت'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Phone',
            field=models.CharField(max_length=15, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='FamilyName',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی کاربر'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Gender_status',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True, verbose_name='جنسیت کاربر'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نام کاربر'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='ProfileImage',
            field=models.ImageField(upload_to='ProfileImage/', verbose_name='پروفایل'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نام بلیت'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Price',
            field=models.IntegerField(verbose_name='قیمت بلیت'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.profilemodel', verbose_name='پروفایل'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='TicketImage',
            field=models.ImageField(upload_to='TicketImage/', verbose_name='بلیت'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.timemodel', verbose_name='زمان بلیت'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.concertmodel', verbose_name='کنسرت'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketSales.locationmodel', verbose_name='مکان برگزاری کنسرت'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Seats',
            field=models.IntegerField(verbose_name='ظرفیت صندلی ها'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='StartDateTime',
            field=models.DateTimeField(verbose_name='زمان شروع فروش بلیت'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Status',
            field=models.CharField(choices=[('Start', 'زمان فروش بلیت آغاز شده است'), ('End', 'زمان فروش بلیت تمام شده است'), ('Cancel', 'کنسرت کنسل شده است'), ('Sale', 'درحال فروش بلیت')], null=True, verbose_name='وضعیت فروش بلیت'),
        ),
    ]
