# Generated by Django 5.2.4 on 2025-08-10 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('ticketSales', '0005_alter_concertmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.profilemodel', verbose_name='پروفایل'),
        ),
        migrations.DeleteModel(
            name='profilemodel',
        ),
    ]
